/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.uno.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.uno.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/uno/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.uno.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.uno.myDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.uno.myDsl.impl.ModelImpl
   * @see org.xtext.example.uno.myDsl.impl.MyDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__RULES = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.uno.myDsl.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.uno.myDsl.impl.RuleImpl
   * @see org.xtext.example.uno.myDsl.impl.MyDslPackageImpl#getRule()
   * @generated
   */
  int RULE = 1;

  /**
   * The feature id for the '<em><b>Objectif</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__OBJECTIF = 0;

  /**
   * The feature id for the '<em><b>Joueur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__JOUEUR = 1;

  /**
   * The feature id for the '<em><b>Regle</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__REGLE = 2;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.uno.myDsl.Objectif <em>Objectif</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.uno.myDsl.Objectif
   * @see org.xtext.example.uno.myDsl.impl.MyDslPackageImpl#getObjectif()
   * @generated
   */
  int OBJECTIF = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.uno.myDsl.Regle <em>Regle</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.uno.myDsl.Regle
   * @see org.xtext.example.uno.myDsl.impl.MyDslPackageImpl#getRegle()
   * @generated
   */
  int REGLE = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.uno.myDsl.Joueur <em>Joueur</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.uno.myDsl.Joueur
   * @see org.xtext.example.uno.myDsl.impl.MyDslPackageImpl#getJoueur()
   * @generated
   */
  int JOUEUR = 4;


  /**
   * Returns the meta object for class '{@link org.xtext.example.uno.myDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.uno.myDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.uno.myDsl.Model#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rules</em>'.
   * @see org.xtext.example.uno.myDsl.Model#getRules()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Rules();

  /**
   * Returns the meta object for class '{@link org.xtext.example.uno.myDsl.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see org.xtext.example.uno.myDsl.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.uno.myDsl.Rule#getObjectif <em>Objectif</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Objectif</em>'.
   * @see org.xtext.example.uno.myDsl.Rule#getObjectif()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Objectif();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.uno.myDsl.Rule#getJoueur <em>Joueur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Joueur</em>'.
   * @see org.xtext.example.uno.myDsl.Rule#getJoueur()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Joueur();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.uno.myDsl.Rule#getRegle <em>Regle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Regle</em>'.
   * @see org.xtext.example.uno.myDsl.Rule#getRegle()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Regle();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.uno.myDsl.Objectif <em>Objectif</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Objectif</em>'.
   * @see org.xtext.example.uno.myDsl.Objectif
   * @generated
   */
  EEnum getObjectif();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.uno.myDsl.Regle <em>Regle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Regle</em>'.
   * @see org.xtext.example.uno.myDsl.Regle
   * @generated
   */
  EEnum getRegle();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.uno.myDsl.Joueur <em>Joueur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Joueur</em>'.
   * @see org.xtext.example.uno.myDsl.Joueur
   * @generated
   */
  EEnum getJoueur();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.uno.myDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.uno.myDsl.impl.ModelImpl
     * @see org.xtext.example.uno.myDsl.impl.MyDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__RULES = eINSTANCE.getModel_Rules();

    /**
     * The meta object literal for the '{@link org.xtext.example.uno.myDsl.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.uno.myDsl.impl.RuleImpl
     * @see org.xtext.example.uno.myDsl.impl.MyDslPackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>Objectif</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__OBJECTIF = eINSTANCE.getRule_Objectif();

    /**
     * The meta object literal for the '<em><b>Joueur</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__JOUEUR = eINSTANCE.getRule_Joueur();

    /**
     * The meta object literal for the '<em><b>Regle</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__REGLE = eINSTANCE.getRule_Regle();

    /**
     * The meta object literal for the '{@link org.xtext.example.uno.myDsl.Objectif <em>Objectif</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.uno.myDsl.Objectif
     * @see org.xtext.example.uno.myDsl.impl.MyDslPackageImpl#getObjectif()
     * @generated
     */
    EEnum OBJECTIF = eINSTANCE.getObjectif();

    /**
     * The meta object literal for the '{@link org.xtext.example.uno.myDsl.Regle <em>Regle</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.uno.myDsl.Regle
     * @see org.xtext.example.uno.myDsl.impl.MyDslPackageImpl#getRegle()
     * @generated
     */
    EEnum REGLE = eINSTANCE.getRegle();

    /**
     * The meta object literal for the '{@link org.xtext.example.uno.myDsl.Joueur <em>Joueur</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.uno.myDsl.Joueur
     * @see org.xtext.example.uno.myDsl.impl.MyDslPackageImpl#getJoueur()
     * @generated
     */
    EEnum JOUEUR = eINSTANCE.getJoueur();

  }

} //MyDslPackage
