/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.uno.myDsl;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Objectif</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.example.uno.myDsl.MyDslPackage#getObjectif()
 * @model
 * @generated
 */
public enum Objectif implements Enumerator
{
  /**
   * The '<em><b>Uno Challenge</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #UNO_CHALLENGE_VALUE
   * @generated
   * @ordered
   */
  UNO_CHALLENGE(0, "UnoChallenge", "Uno Challenge"),

  /**
   * The '<em><b>Classique</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CLASSIQUE_VALUE
   * @generated
   * @ordered
   */
  CLASSIQUE(1, "Classique", "Classique");

  /**
   * The '<em><b>Uno Challenge</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #UNO_CHALLENGE
   * @model name="UnoChallenge" literal="Uno Challenge"
   * @generated
   * @ordered
   */
  public static final int UNO_CHALLENGE_VALUE = 0;

  /**
   * The '<em><b>Classique</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CLASSIQUE
   * @model name="Classique"
   * @generated
   * @ordered
   */
  public static final int CLASSIQUE_VALUE = 1;

  /**
   * An array of all the '<em><b>Objectif</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Objectif[] VALUES_ARRAY =
    new Objectif[]
    {
      UNO_CHALLENGE,
      CLASSIQUE,
    };

  /**
   * A public read-only list of all the '<em><b>Objectif</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Objectif> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Objectif</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Objectif get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Objectif result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Objectif</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Objectif getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Objectif result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Objectif</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Objectif get(int value)
  {
    switch (value)
    {
      case UNO_CHALLENGE_VALUE: return UNO_CHALLENGE;
      case CLASSIQUE_VALUE: return CLASSIQUE;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Objectif(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Objectif
