/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.uno.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.uno.myDsl.Rule#getObjectif <em>Objectif</em>}</li>
 *   <li>{@link org.xtext.example.uno.myDsl.Rule#getJoueur <em>Joueur</em>}</li>
 *   <li>{@link org.xtext.example.uno.myDsl.Rule#getRegle <em>Regle</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.uno.myDsl.MyDslPackage#getRule()
 * @model
 * @generated
 */
public interface Rule extends EObject
{
  /**
   * Returns the value of the '<em><b>Objectif</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.uno.myDsl.Objectif}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objectif</em>' attribute.
   * @see org.xtext.example.uno.myDsl.Objectif
   * @see #setObjectif(Objectif)
   * @see org.xtext.example.uno.myDsl.MyDslPackage#getRule_Objectif()
   * @model
   * @generated
   */
  Objectif getObjectif();

  /**
   * Sets the value of the '{@link org.xtext.example.uno.myDsl.Rule#getObjectif <em>Objectif</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Objectif</em>' attribute.
   * @see org.xtext.example.uno.myDsl.Objectif
   * @see #getObjectif()
   * @generated
   */
  void setObjectif(Objectif value);

  /**
   * Returns the value of the '<em><b>Joueur</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.uno.myDsl.Joueur}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Joueur</em>' attribute.
   * @see org.xtext.example.uno.myDsl.Joueur
   * @see #setJoueur(Joueur)
   * @see org.xtext.example.uno.myDsl.MyDslPackage#getRule_Joueur()
   * @model
   * @generated
   */
  Joueur getJoueur();

  /**
   * Sets the value of the '{@link org.xtext.example.uno.myDsl.Rule#getJoueur <em>Joueur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Joueur</em>' attribute.
   * @see org.xtext.example.uno.myDsl.Joueur
   * @see #getJoueur()
   * @generated
   */
  void setJoueur(Joueur value);

  /**
   * Returns the value of the '<em><b>Regle</b></em>' attribute list.
   * The list contents are of type {@link org.xtext.example.uno.myDsl.Regle}.
   * The literals are from the enumeration {@link org.xtext.example.uno.myDsl.Regle}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Regle</em>' attribute list.
   * @see org.xtext.example.uno.myDsl.Regle
   * @see org.xtext.example.uno.myDsl.MyDslPackage#getRule_Regle()
   * @model unique="false"
   * @generated
   */
  EList<Regle> getRegle();

} // Rule
