/*
 * generated by Xtext 2.23.0
 */
package org.xtext.example.uno.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.uno.ui.internal.UnoActivator;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return UnoActivator.getInstance().getInjector("org.xtext.example.uno.MyDsl");
	}

}
